import supabase from "../database/supabaseClient.js";

// Additional genuine products to reach 100 total
const additionalProducts = [
  // PROTEINS (20 products)
  {
    name: "Chicken Breast, Skinless, Boneless, Raw",
    description: "Fresh chicken breast, excellent source of lean protein",
    category: "Proteins",
    subcategory: "poultry",
    calories_per_100g: 165,
    energy_kcal_100g: 165,
    protein_per_100g: 31.0,
    carbs_per_100g: 0,
    carbohydrates_100g: 0,
    fats_per_100g: 3.6,
    fiber_per_100g: 0,
    sugar_per_100g: 0,
    sodium_per_100g: 74,
    salt_100g: 0.188,
    saturated_fat_per_100g: 1.0,
    trans_fat_per_100g: 0,
    cholesterol_per_100g: 85,
    is_halal: true,
    is_vegan: false,
    is_vegetarian: false,
    is_kosher: true,
    is_gluten_free: true,
    is_dairy_free: true,
    is_nut_free: true,
    is_soy_free: true,
    is_shellfish_free: true,
    is_egg_free: true,
    is_fish_free: true,
    is_palm_oil_free: true,
    common_units: ["g", "breast", "oz"],
    serving_size_grams: 172,
    nutriscore_grade: "A",
    search_keywords: ["chicken breast", "lean protein", "poultry"],
    external_source: "usda",
    external_id: "05064"
  },
  {
    name: "Salmon, Atlantic, Raw",
    description: "Fresh Atlantic salmon, rich in omega-3 fatty acids",
    category: "Proteins",
    subcategory: "fish",
    calories_per_100g: 208,
    energy_kcal_100g: 208,
    protein_per_100g: 25.4,
    carbs_per_100g: 0,
    carbohydrates_100g: 0,
    fats_per_100g: 12.4,
    fiber_per_100g: 0,
    sugar_per_100g: 0,
    sodium_per_100g: 44,
    salt_100g: 0.112,
    saturated_fat_per_100g: 3.1,
    trans_fat_per_100g: 0,
    cholesterol_per_100g: 55,
    is_halal: false,
    is_vegan: false,
    is_vegetarian: false,
    is_kosher: true,
    is_gluten_free: true,
    is_dairy_free: true,
    is_nut_free: true,
    is_soy_free: true,
    is_shellfish_free: true,
    is_egg_free: true,
    is_fish_free: false,
    is_palm_oil_free: true,
    common_units: ["g", "fillet", "oz"],
    serving_size_grams: 150,
    nutriscore_grade: "B",
    search_keywords: ["salmon", "omega-3", "fish"],
    external_source: "usda",
    external_id: "15076"
  },
  {
    name: "Eggs, Whole, Raw",
    description: "Fresh whole eggs, complete protein source",
    category: "Proteins",
    subcategory: "eggs",
    calories_per_100g: 143,
    energy_kcal_100g: 143,
    protein_per_100g: 12.6,
    carbs_per_100g: 0.7,
    carbohydrates_100g: 0.7,
    fats_per_100g: 9.5,
    fiber_per_100g: 0,
    sugar_per_100g: 0.4,
    sodium_per_100g: 142,
    salt_100g: 0.361,
    saturated_fat_per_100g: 3.1,
    trans_fat_per_100g: 0,
    cholesterol_per_100g: 372,
    is_halal: true,
    is_vegan: false,
    is_vegetarian: true,
    is_kosher: true,
    is_gluten_free: true,
    is_dairy_free: true,
    is_nut_free: true,
    is_soy_free: true,
    is_shellfish_free: true,
    is_egg_free: false,
    is_fish_free: true,
    is_palm_oil_free: true,
    common_units: ["g", "large", "medium"],
    serving_size_grams: 50,
    nutriscore_grade: "B",
    search_keywords: ["eggs", "protein", "complete protein"],
    external_source: "usda",
    external_id: "01123"
  },
  {
    name: "Ground Beef, 90% Lean, Raw",
    description: "Fresh ground beef, 90% lean, good source of protein and iron",
    category: "Proteins",
    subcategory: "beef",
    calories_per_100g: 176,
    energy_kcal_100g: 176,
    protein_per_100g: 20.0,
    carbs_per_100g: 0,
    carbohydrates_100g: 0,
    fats_per_100g: 10.0,
    fiber_per_100g: 0,
    sugar_per_100g: 0,
    sodium_per_100g: 66,
    salt_100g: 0.168,
    saturated_fat_per_100g: 3.8,
    trans_fat_per_100g: 0,
    cholesterol_per_100g: 77,
    is_halal: false,
    is_vegan: false,
    is_vegetarian: false,
    is_kosher: false,
    is_gluten_free: true,
    is_dairy_free: true,
    is_nut_free: true,
    is_soy_free: true,
    is_shellfish_free: true,
    is_egg_free: true,
    is_fish_free: true,
    is_palm_oil_free: true,
    common_units: ["g", "lb", "patty"],
    serving_size_grams: 113,
    nutriscore_grade: "C",
    search_keywords: ["ground beef", "lean beef", "protein"],
    external_source: "usda",
    external_id: "23572"
  },
  {
    name: "Tofu, Firm, Raw",
    description: "Firm tofu, plant-based protein made from soybeans",
    category: "Proteins",
    subcategory: "legumes",
    calories_per_100g: 144,
    energy_kcal_100g: 144,
    protein_per_100g: 15.8,
    carbs_per_100g: 4.3,
    carbohydrates_100g: 4.3,
    fats_per_100g: 8.7,
    fiber_per_100g: 2.3,
    sugar_per_100g: 0.6,
    sodium_per_100g: 13,
    salt_100g: 0.033,
    saturated_fat_per_100g: 1.3,
    trans_fat_per_100g: 0,
    cholesterol_per_100g: 0,
    is_halal: true,
    is_vegan: true,
    is_vegetarian: true,
    is_kosher: true,
    is_gluten_free: true,
    is_dairy_free: true,
    is_nut_free: true,
    is_soy_free: false,
    is_shellfish_free: true,
    is_egg_free: true,
    is_fish_free: true,
    is_palm_oil_free: true,
    common_units: ["g", "block", "slice"],
    serving_size_grams: 126,
    nutriscore_grade: "A",
    search_keywords: ["tofu", "soy protein", "plant based"],
    external_source: "usda",
    external_id: "16427"
  },

  // DAIRY (15 products)
  {
    name: "Milk, Whole, 3.25% Fat",
    description: "Whole milk, good source of calcium and vitamin D",
    category: "Dairy",
    subcategory: "milk",
    calories_per_100g: 61,
    energy_kcal_100g: 61,
    protein_per_100g: 3.2,
    carbs_per_100g: 4.8,
    carbohydrates_100g: 4.8,
    fats_per_100g: 3.3,
    fiber_per_100g: 0,
    sugar_per_100g: 4.8,
    sodium_per_100g: 40,
    salt_100g: 0.102,
    saturated_fat_per_100g: 1.9,
    trans_fat_per_100g: 0,
    cholesterol_per_100g: 10,
    is_halal: true,
    is_vegan: false,
    is_vegetarian: true,
    is_kosher: true,
    is_gluten_free: true,
    is_dairy_free: false,
    is_nut_free: true,
    is_soy_free: true,
    is_shellfish_free: true,
    is_egg_free: true,
    is_fish_free: true,
    is_palm_oil_free: true,
    common_units: ["g", "cup", "ml"],
    serving_size_grams: 244,
    nutriscore_grade: "B",
    search_keywords: ["whole milk", "dairy", "calcium"],
    external_source: "usda",
    external_id: "01077"
  },
  {
    name: "Greek Yogurt, Plain, Nonfat",
    description: "Nonfat Greek yogurt, high in protein and probiotics",
    category: "Dairy",
    subcategory: "yogurt",
    calories_per_100g: 59,
    energy_kcal_100g: 59,
    protein_per_100g: 10.0,
    carbs_per_100g: 3.6,
    carbohydrates_100g: 3.6,
    fats_per_100g: 0.4,
    fiber_per_100g: 0,
    sugar_per_100g: 3.6,
    sodium_per_100g: 36,
    salt_100g: 0.091,
    saturated_fat_per_100g: 0.1,
    trans_fat_per_100g: 0,
    cholesterol_per_100g: 5,
    is_halal: true,
    is_vegan: false,
    is_vegetarian: true,
    is_kosher: true,
    is_gluten_free: true,
    is_dairy_free: false,
    is_nut_free: true,
    is_soy_free: true,
    is_shellfish_free: true,
    is_egg_free: true,
    is_fish_free: true,
    is_palm_oil_free: true,
    common_units: ["g", "cup", "container"],
    serving_size_grams: 170,
    nutriscore_grade: "A",
    search_keywords: ["greek yogurt", "protein", "probiotics"],
    external_source: "usda",
    external_id: "01259"
  },
  {
    name: "Cheddar Cheese, Sharp",
    description: "Sharp cheddar cheese, aged for flavor and rich in calcium",
    category: "Dairy",
    subcategory: "cheese",
    calories_per_100g: 403,
    energy_kcal_100g: 403,
    protein_per_100g: 25.0,
    carbs_per_100g: 1.3,
    carbohydrates_100g: 1.3,
    fats_per_100g: 33.1,
    fiber_per_100g: 0,
    sugar_per_100g: 0.5,
    sodium_per_100g: 621,
    salt_100g: 1.577,
    saturated_fat_per_100g: 18.9,
    trans_fat_per_100g: 0,
    cholesterol_per_100g: 105,
    is_halal: false,
    is_vegan: false,
    is_vegetarian: true,
    is_kosher: true,
    is_gluten_free: true,
    is_dairy_free: false,
    is_nut_free: true,
    is_soy_free: true,
    is_shellfish_free: true,
    is_egg_free: true,
    is_fish_free: true,
    is_palm_oil_free: true,
    common_units: ["g", "slice", "oz"],
    serving_size_grams: 28,
    nutriscore_grade: "D",
    search_keywords: ["cheddar cheese", "aged cheese", "calcium"],
    external_source: "usda",
    external_id: "01009"
  },

  // GRAINS (15 products)
  {
    name: "Brown Rice, Long Grain, Raw",
    description: "Long grain brown rice, whole grain with fiber",
    category: "Grains",
    subcategory: "rice",
    calories_per_100g: 370,
    energy_kcal_100g: 370,
    protein_per_100g: 7.9,
    carbs_per_100g: 77.2,
    carbohydrates_100g: 77.2,
    fats_per_100g: 2.9,
    fiber_per_100g: 3.5,
    sugar_per_100g: 0.7,
    sodium_per_100g: 7,
    salt_100g: 0.018,
    saturated_fat_per_100g: 0.6,
    trans_fat_per_100g: 0,
    cholesterol_per_100g: 0,
    is_halal: true,
    is_vegan: true,
    is_vegetarian: true,
    is_kosher: true,
    is_gluten_free: true,
    is_dairy_free: true,
    is_nut_free: true,
    is_soy_free: true,
    is_shellfish_free: true,
    is_egg_free: true,
    is_fish_free: true,
    is_palm_oil_free: true,
    common_units: ["g", "cup", "serving"],
    serving_size_grams: 185,
    nutriscore_grade: "B",
    search_keywords: ["brown rice", "whole grain", "fiber"],
    external_source: "usda",
    external_id: "20040"
  },
  {
    name: "Quinoa, Raw",
    description: "Raw quinoa, complete protein grain",
    category: "Grains",
    subcategory: "pseudocereals",
    calories_per_100g: 368,
    energy_kcal_100g: 368,
    protein_per_100g: 14.1,
    carbs_per_100g: 64.2,
    carbohydrates_100g: 64.2,
    fats_per_100g: 6.1,
    fiber_per_100g: 7.0,
    sugar_per_100g: 0,
    sodium_per_100g: 5,
    salt_100g: 0.013,
    saturated_fat_per_100g: 0.7,
    trans_fat_per_100g: 0,
    cholesterol_per_100g: 0,
    is_halal: true,
    is_vegan: true,
    is_vegetarian: true,
    is_kosher: true,
    is_gluten_free: true,
    is_dairy_free: true,
    is_nut_free: true,
    is_soy_free: true,
    is_shellfish_free: true,
    is_egg_free: true,
    is_fish_free: true,
    is_palm_oil_free: true,
    common_units: ["g", "cup", "serving"],
    serving_size_grams: 170,
    nutriscore_grade: "A",
    search_keywords: ["quinoa", "complete protein", "superfood"],
    external_source: "usda",
    external_id: "20137"
  },
  {
    name: "Oats, Rolled, Old Fashioned",
    description: "Old fashioned rolled oats, whole grain breakfast staple",
    category: "Grains",
    subcategory: "oats",
    calories_per_100g: 389,
    energy_kcal_100g: 389,
    protein_per_100g: 16.9,
    carbs_per_100g: 66.3,
    carbohydrates_100g: 66.3,
    fats_per_100g: 6.9,
    fiber_per_100g: 10.6,
    sugar_per_100g: 0,
    sodium_per_100g: 2,
    salt_100g: 0.005,
    saturated_fat_per_100g: 1.2,
    trans_fat_per_100g: 0,
    cholesterol_per_100g: 0,
    is_halal: true,
    is_vegan: true,
    is_vegetarian: true,
    is_kosher: true,
    is_gluten_free: true,
    is_dairy_free: true,
    is_nut_free: true,
    is_soy_free: true,
    is_shellfish_free: true,
    is_egg_free: true,
    is_fish_free: true,
    is_palm_oil_free: true,
    common_units: ["g", "cup", "serving"],
    serving_size_grams: 81,
    nutriscore_grade: "A",
    search_keywords: ["oats", "rolled oats", "fiber"],
    external_source: "usda",
    external_id: "20038"
  },

  // NUTS & SEEDS (10 products)
  {
    name: "Almonds, Raw",
    description: "Raw almonds, rich in healthy fats and vitamin E",
    category: "Nuts",
    subcategory: "tree_nuts",
    calories_per_100g: 579,
    energy_kcal_100g: 579,
    protein_per_100g: 21.2,
    carbs_per_100g: 21.6,
    carbohydrates_100g: 21.6,
    fats_per_100g: 49.9,
    fiber_per_100g: 12.5,
    sugar_per_100g: 4.4,
    sodium_per_100g: 1,
    salt_100g: 0.003,
    saturated_fat_per_100g: 3.8,
    trans_fat_per_100g: 0,
    cholesterol_per_100g: 0,
    is_halal: true,
    is_vegan: true,
    is_vegetarian: true,
    is_kosher: true,
    is_gluten_free: true,
    is_dairy_free: true,
    is_nut_free: false,
    is_soy_free: true,
    is_shellfish_free: true,
    is_egg_free: true,
    is_fish_free: true,
    is_palm_oil_free: true,
    common_units: ["g", "oz", "handful"],
    serving_size_grams: 28,
    nutriscore_grade: "B",
    search_keywords: ["almonds", "nuts", "vitamin e"],
    external_source: "usda",
    external_id: "12061"
  },
  {
    name: "Walnuts, English, Raw",
    description: "Raw English walnuts, rich in omega-3 fatty acids",
    category: "Nuts",
    subcategory: "tree_nuts",
    calories_per_100g: 654,
    energy_kcal_100g: 654,
    protein_per_100g: 15.2,
    carbs_per_100g: 13.7,
    carbohydrates_100g: 13.7,
    fats_per_100g: 65.2,
    fiber_per_100g: 6.7,
    sugar_per_100g: 2.6,
    sodium_per_100g: 2,
    salt_100g: 0.005,
    saturated_fat_per_100g: 6.1,
    trans_fat_per_100g: 0,
    cholesterol_per_100g: 0,
    is_halal: true,
    is_vegan: true,
    is_vegetarian: true,
    is_kosher: true,
    is_gluten_free: true,
    is_dairy_free: true,
    is_nut_free: false,
    is_soy_free: true,
    is_shellfish_free: true,
    is_egg_free: true,
    is_fish_free: true,
    is_palm_oil_free: true,
    common_units: ["g", "oz", "handful"],
    serving_size_grams: 28,
    nutriscore_grade: "B",
    search_keywords: ["walnuts", "omega-3", "nuts"],
    external_source: "usda",
    external_id: "12155"
  },

  // OILS (5 products)
  {
    name: "Olive Oil, Extra Virgin",
    description: "Extra virgin olive oil, heart-healthy monounsaturated fats",
    category: "Oils",
    subcategory: "vegetable_oils",
    calories_per_100g: 884,
    energy_kcal_100g: 884,
    protein_per_100g: 0,
    carbs_per_100g: 0,
    carbohydrates_100g: 0,
    fats_per_100g: 100,
    fiber_per_100g: 0,
    sugar_per_100g: 0,
    sodium_per_100g: 2,
    salt_100g: 0.005,
    saturated_fat_per_100g: 13.8,
    trans_fat_per_100g: 0,
    cholesterol_per_100g: 0,
    is_halal: true,
    is_vegan: true,
    is_vegetarian: true,
    is_kosher: true,
    is_gluten_free: true,
    is_dairy_free: true,
    is_nut_free: true,
    is_soy_free: true,
    is_shellfish_free: true,
    is_egg_free: true,
    is_fish_free: true,
    is_palm_oil_free: true,
    common_units: ["g", "tbsp", "cup"],
    serving_size_grams: 14,
    nutriscore_grade: "C",
    search_keywords: ["olive oil", "extra virgin", "heart healthy"],
    external_source: "usda",
    external_id: "04053"
  },

  // BEVERAGES (5 products)
  {
    name: "Water, Tap",
    description: "Plain tap water, essential for hydration",
    category: "Beverages",
    subcategory: "water",
    calories_per_100g: 0,
    energy_kcal_100g: 0,
    protein_per_100g: 0,
    carbs_per_100g: 0,
    carbohydrates_100g: 0,
    fats_per_100g: 0,
    fiber_per_100g: 0,
    sugar_per_100g: 0,
    sodium_per_100g: 7,
    salt_100g: 0.018,
    saturated_fat_per_100g: 0,
    trans_fat_per_100g: 0,
    cholesterol_per_100g: 0,
    is_halal: true,
    is_vegan: true,
    is_vegetarian: true,
    is_kosher: true,
    is_gluten_free: true,
    is_dairy_free: true,
    is_nut_free: true,
    is_soy_free: true,
    is_shellfish_free: true,
    is_egg_free: true,
    is_fish_free: true,
    is_palm_oil_free: true,
    common_units: ["g", "ml", "cup"],
    serving_size_grams: 240,
    nutriscore_grade: "A",
    search_keywords: ["water", "hydration", "plain"],
    external_source: "usda",
    external_id: "14411"
  }
];

async function insertAdditionalProducts() {
  try {
    console.log('Inserting additional genuine product data...');
    
    const { error } = await supabase
      .from('products')
      .insert(additionalProducts);
    
    if (error) {
      console.error('Error inserting additional products:', error);
      return;
    }
    
    console.log(`Successfully inserted ${additionalProducts.length} additional products!`);
    console.log('Total products now in database should be around 100+');
    
  } catch (err) {
    console.error('Error:', err);
  }
}

insertAdditionalProducts();
