import supabase from "../database/supabaseClient.js";

// Genuine product data based on USDA FoodData Central and other reliable sources
const genuineProducts = [
  // FRUITS
  {
    name: "Apple, Raw, with Skin",
    description: "Fresh apple with skin, excellent source of fiber and vitamin C",
    category: "Fruits",
    subcategory: "pome_fruits",
    calories_per_100g: 52,
    energy_kcal_100g: 52,
    protein_per_100g: 0.3,
    carbs_per_100g: 13.8,
    carbohydrates_100g: 13.8,
    fats_per_100g: 0.2,
    fiber_per_100g: 2.4,
    sugar_per_100g: 10.4,
    sodium_per_100g: 1,
    salt_100g: 0.003,
    saturated_fat_per_100g: 0.03,
    trans_fat_per_100g: 0,
    cholesterol_per_100g: 0,
    is_halal: true,
    is_vegan: true,
    is_vegetarian: true,
    is_kosher: true,
    is_gluten_free: true,
    is_dairy_free: true,
    is_nut_free: true,
    is_soy_free: true,
    is_shellfish_free: true,
    is_egg_free: true,
    is_fish_free: true,
    is_palm_oil_free: true,
    common_units: ["g", "medium", "cup", "slice"],
    serving_size_grams: 182,
    nutriscore_grade: "A",
    search_keywords: ["apple", "fruit", "fresh", "vitamin c", "fiber"],
    external_source: "usda",
    external_id: "09003"
  },
  {
    name: "Banana, Raw",
    description: "Fresh banana, rich in potassium and natural sugars",
    category: "Fruits",
    subcategory: "tropical_fruits",
    calories_per_100g: 89,
    energy_kcal_100g: 89,
    protein_per_100g: 1.1,
    carbs_per_100g: 22.8,
    carbohydrates_100g: 22.8,
    fats_per_100g: 0.3,
    fiber_per_100g: 2.6,
    sugar_per_100g: 12.2,
    sodium_per_100g: 1,
    salt_100g: 0.003,
    saturated_fat_per_100g: 0.1,
    trans_fat_per_100g: 0,
    cholesterol_per_100g: 0,
    is_halal: true,
    is_vegan: true,
    is_vegetarian: true,
    is_kosher: true,
    is_gluten_free: true,
    is_dairy_free: true,
    is_nut_free: true,
    is_soy_free: true,
    is_shellfish_free: true,
    is_egg_free: true,
    is_fish_free: true,
    is_palm_oil_free: true,
    common_units: ["g", "medium", "large", "cup"],
    serving_size_grams: 118,
    nutriscore_grade: "A",
    search_keywords: ["banana", "fruit", "potassium", "energy", "natural"],
    external_source: "usda",
    external_id: "09040"
  },
  {
    name: "Orange, Raw, Navel",
    description: "Fresh navel orange, excellent source of vitamin C",
    category: "Fruits",
    subcategory: "citrus_fruits",
    calories_per_100g: 47,
    energy_kcal_100g: 47,
    protein_per_100g: 0.9,
    carbs_per_100g: 11.8,
    carbohydrates_100g: 11.8,
    fats_per_100g: 0.1,
    fiber_per_100g: 2.4,
    sugar_per_100g: 9.4,
    sodium_per_100g: 0,
    salt_100g: 0,
    saturated_fat_per_100g: 0.02,
    trans_fat_per_100g: 0,
    cholesterol_per_100g: 0,
    is_halal: true,
    is_vegan: true,
    is_vegetarian: true,
    is_kosher: true,
    is_gluten_free: true,
    is_dairy_free: true,
    is_nut_free: true,
    is_soy_free: true,
    is_shellfish_free: true,
    is_egg_free: true,
    is_fish_free: true,
    is_palm_oil_free: true,
    common_units: ["g", "medium", "large", "cup"],
    serving_size_grams: 140,
    nutriscore_grade: "A",
    search_keywords: ["orange", "citrus", "vitamin c", "fresh", "navel"],
    external_source: "usda",
    external_id: "09200"
  },
  {
    name: "Blueberries, Raw",
    description: "Fresh blueberries, packed with antioxidants",
    category: "Fruits",
    subcategory: "berries",
    calories_per_100g: 57,
    energy_kcal_100g: 57,
    protein_per_100g: 0.7,
    carbs_per_100g: 14.5,
    carbohydrates_100g: 14.5,
    fats_per_100g: 0.3,
    fiber_per_100g: 2.4,
    sugar_per_100g: 10.0,
    sodium_per_100g: 1,
    salt_100g: 0.003,
    saturated_fat_per_100g: 0.03,
    trans_fat_per_100g: 0,
    cholesterol_per_100g: 0,
    is_halal: true,
    is_vegan: true,
    is_vegetarian: true,
    is_kosher: true,
    is_gluten_free: true,
    is_dairy_free: true,
    is_nut_free: true,
    is_soy_free: true,
    is_shellfish_free: true,
    is_egg_free: true,
    is_fish_free: true,
    is_palm_oil_free: true,
    common_units: ["g", "cup", "pint", "handful"],
    serving_size_grams: 148,
    nutriscore_grade: "A",
    search_keywords: ["blueberries", "berries", "antioxidants", "superfood", "fresh"],
    external_source: "usda",
    external_id: "09050"
  },
  {
    name: "Strawberries, Raw",
    description: "Fresh strawberries, rich in vitamin C and folate",
    category: "Fruits",
    subcategory: "berries",
    calories_per_100g: 32,
    energy_kcal_100g: 32,
    protein_per_100g: 0.7,
    carbs_per_100g: 7.7,
    carbohydrates_100g: 7.7,
    fats_per_100g: 0.3,
    fiber_per_100g: 2.0,
    sugar_per_100g: 4.9,
    sodium_per_100g: 1,
    salt_100g: 0.003,
    saturated_fat_per_100g: 0.02,
    trans_fat_per_100g: 0,
    cholesterol_per_100g: 0,
    is_halal: true,
    is_vegan: true,
    is_vegetarian: true,
    is_kosher: true,
    is_gluten_free: true,
    is_dairy_free: true,
    is_nut_free: true,
    is_soy_free: true,
    is_shellfish_free: true,
    is_egg_free: true,
    is_fish_free: true,
    is_palm_oil_free: true,
    common_units: ["g", "cup", "pint", "medium"],
    serving_size_grams: 152,
    nutriscore_grade: "A",
    search_keywords: ["strawberries", "berries", "vitamin c", "fresh", "sweet"],
    external_source: "usda",
    external_id: "09316"
  }
];

// Add more products in batches to avoid token limits
const moreProducts = [
  // VEGETABLES
  {
    name: "Broccoli, Raw",
    description: "Fresh broccoli, excellent source of vitamin C and K",
    category: "Vegetables",
    subcategory: "cruciferous",
    calories_per_100g: 34,
    energy_kcal_100g: 34,
    protein_per_100g: 2.8,
    carbs_per_100g: 6.6,
    carbohydrates_100g: 6.6,
    fats_per_100g: 0.4,
    fiber_per_100g: 2.6,
    sugar_per_100g: 1.5,
    sodium_per_100g: 33,
    salt_100g: 0.084,
    saturated_fat_per_100g: 0.04,
    trans_fat_per_100g: 0,
    cholesterol_per_100g: 0,
    is_halal: true,
    is_vegan: true,
    is_vegetarian: true,
    is_kosher: true,
    is_gluten_free: true,
    is_dairy_free: true,
    is_nut_free: true,
    is_soy_free: true,
    is_shellfish_free: true,
    is_egg_free: true,
    is_fish_free: true,
    is_palm_oil_free: true,
    common_units: ["g", "cup", "floret", "head"],
    serving_size_grams: 91,
    nutriscore_grade: "A",
    search_keywords: ["broccoli", "vegetable", "vitamin c", "cruciferous", "healthy"],
    external_source: "usda",
    external_id: "11090"
  },
  {
    name: "Spinach, Raw",
    description: "Fresh spinach, rich in iron and folate",
    category: "Vegetables",
    subcategory: "leafy_greens",
    calories_per_100g: 23,
    energy_kcal_100g: 23,
    protein_per_100g: 2.9,
    carbs_per_100g: 3.6,
    carbohydrates_100g: 3.6,
    fats_per_100g: 0.4,
    fiber_per_100g: 2.2,
    sugar_per_100g: 0.4,
    sodium_per_100g: 79,
    salt_100g: 0.201,
    saturated_fat_per_100g: 0.06,
    trans_fat_per_100g: 0,
    cholesterol_per_100g: 0,
    is_halal: true,
    is_vegan: true,
    is_vegetarian: true,
    is_kosher: true,
    is_gluten_free: true,
    is_dairy_free: true,
    is_nut_free: true,
    is_soy_free: true,
    is_shellfish_free: true,
    is_egg_free: true,
    is_fish_free: true,
    is_palm_oil_free: true,
    common_units: ["g", "cup", "bunch", "leaf"],
    serving_size_grams: 30,
    nutriscore_grade: "A",
    search_keywords: ["spinach", "leafy greens", "iron", "folate", "fresh"],
    external_source: "usda",
    external_id: "10057"
  },
  {
    name: "Carrot, Raw",
    description: "Fresh carrot, rich in beta-carotene and vitamin A",
    category: "Vegetables",
    subcategory: "root_vegetables",
    calories_per_100g: 41,
    energy_kcal_100g: 41,
    protein_per_100g: 0.9,
    carbs_per_100g: 9.6,
    carbohydrates_100g: 9.6,
    fats_per_100g: 0.2,
    fiber_per_100g: 2.8,
    sugar_per_100g: 4.7,
    sodium_per_100g: 69,
    salt_100g: 0.175,
    saturated_fat_per_100g: 0.03,
    trans_fat_per_100g: 0,
    cholesterol_per_100g: 0,
    is_halal: true,
    is_vegan: true,
    is_vegetarian: true,
    is_kosher: true,
    is_gluten_free: true,
    is_dairy_free: true,
    is_nut_free: true,
    is_soy_free: true,
    is_shellfish_free: true,
    is_egg_free: true,
    is_fish_free: true,
    is_palm_oil_free: true,
    common_units: ["g", "medium", "large", "cup"],
    serving_size_grams: 61,
    nutriscore_grade: "A",
    search_keywords: ["carrot", "root vegetable", "beta carotene", "vitamin a", "crunchy"],
    external_source: "usda",
    external_id: "11124"
  },
  {
    name: "Tomato, Red, Ripe, Raw",
    description: "Fresh red tomato, rich in lycopene and vitamin C",
    category: "Vegetables",
    subcategory: "nightshades",
    calories_per_100g: 18,
    energy_kcal_100g: 18,
    protein_per_100g: 0.9,
    carbs_per_100g: 3.9,
    carbohydrates_100g: 3.9,
    fats_per_100g: 0.2,
    fiber_per_100g: 1.2,
    sugar_per_100g: 2.6,
    sodium_per_100g: 5,
    salt_100g: 0.013,
    saturated_fat_per_100g: 0.03,
    trans_fat_per_100g: 0,
    cholesterol_per_100g: 0,
    is_halal: true,
    is_vegan: true,
    is_vegetarian: true,
    is_kosher: true,
    is_gluten_free: true,
    is_dairy_free: true,
    is_nut_free: true,
    is_soy_free: true,
    is_shellfish_free: true,
    is_egg_free: true,
    is_fish_free: true,
    is_palm_oil_free: true,
    common_units: ["g", "medium", "large", "cup"],
    serving_size_grams: 123,
    nutriscore_grade: "A",
    search_keywords: ["tomato", "lycopene", "vitamin c", "fresh", "red"],
    external_source: "usda",
    external_id: "11529"
  },
  {
    name: "Cucumber, Raw, with Peel",
    description: "Fresh cucumber with peel, hydrating and low-calorie",
    category: "Vegetables",
    subcategory: "cucurbits",
    calories_per_100g: 16,
    energy_kcal_100g: 16,
    protein_per_100g: 0.7,
    carbs_per_100g: 4.0,
    carbohydrates_100g: 4.0,
    fats_per_100g: 0.1,
    fiber_per_100g: 0.5,
    sugar_per_100g: 1.7,
    sodium_per_100g: 2,
    salt_100g: 0.005,
    saturated_fat_per_100g: 0.04,
    trans_fat_per_100g: 0,
    cholesterol_per_100g: 0,
    is_halal: true,
    is_vegan: true,
    is_vegetarian: true,
    is_kosher: true,
    is_gluten_free: true,
    is_dairy_free: true,
    is_nut_free: true,
    is_soy_free: true,
    is_shellfish_free: true,
    is_egg_free: true,
    is_fish_free: true,
    is_palm_oil_free: true,
    common_units: ["g", "medium", "large", "cup"],
    serving_size_grams: 119,
    nutriscore_grade: "A",
    search_keywords: ["cucumber", "hydrating", "low calorie", "fresh", "cooling"],
    external_source: "usda",
    external_id: "11205"
  }
];

async function insertProducts() {
  try {
    console.log('Inserting genuine product data...');
    
    // Insert first batch
    const { error: error1 } = await supabase
      .from('products')
      .insert(genuineProducts);
    
    if (error1) {
      console.error('Error inserting first batch:', error1);
      return;
    }
    
    // Insert second batch
    const { error: error2 } = await supabase
      .from('products')
      .insert(moreProducts);
    
    if (error2) {
      console.error('Error inserting second batch:', error2);
      return;
    }
    
    console.log('Successfully inserted genuine product data!');
    console.log(`Total products inserted: ${genuineProducts.length + moreProducts.length}`);
    
  } catch (err) {
    console.error('Error:', err);
  }
}

insertProducts();
